---
title: "Data Import"
output: html_document
---
```{r}
library(tidyverse)
library(readxl)
library(haven)
```

Import our first dataset 
```{r}
litters_df =
  read_csv(file= "data_import_examples/FAS_litters.csv")

litters_df = janitor:: clean_names(litters_df)
```
Import your second dataset 
```{r}
pups_df =
  read_csv( "data_import_examples/FAS_pups.csv", skip = 3)
pups_df = janitor:: clean_names(pups_df)
```


### Look at the data 

```{r}
litters_df
pups_df
```

Head or tail 
```{r}
head(litters_df, 20)
tail(pups_df, 5)
```
```{r}
skimr::skim(pups_df)
```
```{r}
litters_df = 
    read_csv(
        file = "data_import_examples/FAS_litters.csv",
        na = c(".", "NA", ".")
        )
litters_df = janitor:: clean_names(litters_df)
```

```{r}
pups_df =
  read_csv(
    file ="data_import_examples/FAS_pups.csv", skip = 3,
    na = c(".", "NA", ".")
        )
pups_df = janitor:: clean_names(pups_df)
```

## Oh excel...

Jenny Bryan made "readxl" to solve our problems 
```{r}
mlb_df = read_excel("data_import_examples/mlb11.xlsx")
```
Look at the data 
```{r}
mlb_df
```
Load some Lotr data 

import Fellowship of the Ring words 
```{r}
fotr_df =
  read_excel(
    "data_import_examples/LotR_Words.xlsx",
    range = "B3:D6")
fotr_df
```
```{r}
tt_df =
  read_excel(
    "data_import_examples/LotR_Words.xlsx",
    range = "F3:H6")
tt_df
```

#Import SAS
Read in the PULSE dataset 

```{r}
pulse_df =
  read_sas("data_import_examples/public_pulse_data.sas7bdat")

pulse_df = janitor::clean_names(pulse_df)
```

#Whats so bad about "read.csv()
Import pups with "readcsv()
```{r}
pups_df_base =
  read.csv("data_import_examples/FAS_pups.csv")
  pups_df_base
```
Wont show: lazy about variable names: super slow for big dataset. 






